---
title: "Analysis of *Styela plicata*"
author: "Paule Mathieu"
format: html
editor: visual
---

## *Styela plicata*

This document relates only to the S. plicata data.


```{r, results='hide'}
source("data_wrangling.R")
```

### Objective 1: Evaluate Styela recolonization across all sampling periods

```{r}
# rearrange sampling periods accordingly
styela$Sampling_period <- factor(styela$Sampling_period, levels = c("S1", "S2", "S3", "S4"))

table(styela$Sampling_period)
```

```{r}
# styela count, mean, se
styela_count_summary <- styela %>%
  group_by(Sampling_period) %>%
  summarise(
    mean_count = mean(styela_count, na.rm = TRUE),
    sd_count = sd(styela_count, na.rm = TRUE),
    n = sum(!is.na(styela_count)),
    se_count = sd_count / sqrt(n))

styela_count_model <- glmmTMB(
  styela_count ~ Sampling_period + (1 | Panel_ID),
  family = nbinom2,
  data = styela)
summary(styela_count_model)
```

```{r}
# illustrate count data per sampling period
ggplot(styela, aes(x = Sampling_period, y = styela_count)) +
  #geom_boxplot(fill = "#FFB6C1", width = 0.6, outlier.shape = NA) + #testing options
  #geom_jitter(width = 0.12, alpha = 0.35, size = 1.5) +
  stat_summary(fun = mean, geom = "point", shape = 23, size = 5, fill = "#FFB6C1", colour = "black", stroke = 1) +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.15) +
  labs(x = "Sampling period", y = "Styela abundance (nb of individuals)") +
  theme_pub()
```

```{r}
# styela biomass, mean, se
styela_biomass <- styela %>%
  group_by(Sampling_period) %>%
  summarise(
    mean_biomass = mean(Styela_dry_weight, na.rm = TRUE),
    sd_biomass = sd(Styela_dry_weight, na.rm = TRUE),
    n = sum(!is.na(Styela_dry_weight)),
    se_biomass = sd_biomass / sqrt(n))
```

```{r}
# illustrate biomass data per sampling period
ggplot(styela, aes(x = Sampling_period, y = Styela_dry_weight)) +
  stat_summary(fun = mean, geom = "point", shape = 23, size = 5, fill = "#FFB6C1", colour = "black", stroke = 1) +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.15) +
  labs(x = "Sampling period", y = "Styela dry biomass (g)") +
  theme_pub()
```

### Objective 2: Assess how Styela recolonization varies with depth

```{r}
# styela abundance per depth across sampling periods

ggplot(styela, aes(x = Depth, y = styela_count)) +
  stat_summary(fun = mean, geom = "point", shape = 23, size = 3, fill = "#FFB6C1", colour = "black", stroke = 1) +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.15) +
  facet_wrap(~Sampling_period) +
  labs(x = "Depth", y = "Styela abundance (nb of individuals)") +
  theme_pub() +
        theme(strip.background = element_rect(fill = "grey90", colour = "black"))
```
```{r}
# styela biomass per depth across sampling period

ggplot(styela, aes(x = Depth, y = Styela_dry_weight)) +
  stat_summary(fun = mean, geom = "point", shape = 23, size = 3, fill = "#FFB6C1", colour = "black", stroke = 1) +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.15) +
  facet_wrap(~Sampling_period) +
  labs(x = "Depth", y = "Styela dry biomass (g)") +
  theme_pub() +
        theme(strip.background = element_rect(fill = "grey90", colour = "black"))
```

### Objective 3: Identifying problematic panels

```{r}
ggplot(styela, aes(x = Panel_front, y = Styela_dry_weight)) +
  geom_boxplot(fill = "#FFB6C1", width = 0.6, outlier.shape = NA) +
  #geom_jitter(width = 0.12, alpha = 0.35, size = 1.5) +
  stat_summary(fun = mean, geom = "point", shape = 18, size = 3) +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.15) +
  labs(x = "Panel design", y = "Styela dry biomass (g)") +
         coord_cartesian(ylim = c(0, 15)) +
  theme_pub()
```




